apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: test
  description: some description
  annotations:
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: test
  lifecycle: production